"""allow duplicate invoice_number

Revision ID: 1663b6cab694
Revises: c390080b950f
Create Date: 2026-10-06 14:27:49.961412

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1663b6cab694'
down_revision = 'c390080b950f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sales', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_sales_invoice_number'))
        batch_op.create_index(batch_op.f('ix_sales_invoice_number'), ['invoice_number'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sales', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_sales_invoice_number'))
        batch_op.create_index(batch_op.f('ix_sales_invoice_number'), ['invoice_number'], unique=True)

    # ### end Alembic commands ###
