"""Change invoice_date column type to String

Revision ID: d466ef1123cc
Revises: 1663b6cab694
Create Date: 2026-10-08 12:57:02.280412

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd466ef1123cc'
down_revision = '1663b6cab694'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sales', schema=None) as batch_op:
        batch_op.alter_column('invoice_date',
               existing_type=sa.DATE(),
               type_=sa.String(length=100),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sales', schema=None) as batch_op:
        batch_op.alter_column('invoice_date',
               existing_type=sa.String(length=100),
               type_=sa.DATE(),
               nullable=False)

    # ### end Alembic commands ###
